# Generated by Django 4.0.2 on 2022-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_widget_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
